import type {
  Fund,
  LP,
  BankerContact,
  Deal,
  Task,
  EventFeedItem,
  SimulationState,
} from "./types";

export const SEED_FUND: Fund = {
  id: "fund-1",
  name: "Arcadia Capital Partners I",
  vintage: 2026,
  targetSize: 150,
  committedCapital: 47,
  calledCapital: 12,
  strategy: "Lower Middle Market Buyout",
  sector: "Business Services & Industrials",
  geography: "North America",
  revenueMin: 10,
  revenueMax: 75,
  ebitdaMin: 2,
  ebitdaMax: 12,
  fundingStatus: "fundraising",
  managementFee: 2.0,
  carry: 20,
  investmentPeriodYears: 5,
  fundLifeYears: 10,
};

export const SEED_LPS: LP[] = [
  {
    id: "lp-1",
    name: "Hargrove Family Office",
    type: "family_office",
    targetCommitment: 15,
    committedAmount: 15,
    status: "committed",
    contactName: "Richard Hargrove III",
    contactTitle: "CIO",
    location: "Greenwich, CT",
    introductionDate: "2025-09-10",
    lastContactDate: "2026-03-15",
    notes: "Strong relationship. Co-invested alongside GP in prior fund. Very supportive.",
    tier: 1,
  },
  {
    id: "lp-2",
    name: "Meridian University Endowment",
    type: "endowment",
    targetCommitment: 25,
    committedAmount: 20,
    status: "committed",
    contactName: "Patricia Walsh",
    contactTitle: "Director of Alternatives",
    location: "Boston, MA",
    introductionDate: "2025-08-02",
    lastContactDate: "2026-04-01",
    notes: "Requires quarterly reporting. Highly process-driven. IC approval pending final close.",
    tier: 1,
  },
  {
    id: "lp-3",
    name: "Vantage Point Capital FOF",
    type: "fund_of_funds",
    targetCommitment: 20,
    committedAmount: 12,
    status: "soft_commit",
    contactName: "James Cho",
    contactTitle: "Managing Director",
    location: "New York, NY",
    introductionDate: "2025-10-20",
    lastContactDate: "2026-03-28",
    notes: "Reviewing DDQ responses. Wants to see 2-3 LOIs before finalizing commitment.",
    tier: 1,
  },
  {
    id: "lp-4",
    name: "Clearwater Pension Fund",
    type: "pension",
    targetCommitment: 30,
    committedAmount: 0,
    status: "prospect",
    contactName: "Susan Olawale",
    contactTitle: "Head of PE Allocation",
    location: "Chicago, IL",
    introductionDate: "2026-01-14",
    lastContactDate: "2026-02-20",
    notes: "Board meeting in June. Needs audited track record. Long lead time typical.",
    tier: 2,
  },
  {
    id: "lp-5",
    name: "Thornwood HNW Group",
    type: "hnw",
    targetCommitment: 5,
    committedAmount: 0,
    status: "prospect",
    contactName: "Daniel Park",
    contactTitle: "Wealth Manager",
    location: "Dallas, TX",
    introductionDate: "2026-02-05",
    lastContactDate: "2026-04-10",
    notes: "Smaller check but highly networked. May open doors to other family offices in Texas.",
    tier: 3,
  },
];

export const SEED_BANKERS: BankerContact[] = [
  {
    id: "banker-1",
    name: "Michael Torres",
    firm: "Lincoln International",
    title: "Managing Director",
    coverage: "Business Services",
    dealsShared: 4,
    lastInteraction: "2026-04-18",
    relationship: "active",
    email: "m.torres@lincolninternational.com",
    phone: "(312) 555-0192",
  },
  {
    id: "banker-2",
    name: "Caroline Strickland",
    firm: "Harris Williams",
    title: "Vice President",
    coverage: "Industrials & Manufacturing",
    dealsShared: 3,
    lastInteraction: "2026-04-05",
    relationship: "warm",
    email: "c.strickland@harriswilliams.com",
    phone: "(804) 555-0341",
  },
  {
    id: "banker-3",
    name: "Kevin Zhao",
    firm: "Houlihan Lokey",
    title: "Director",
    coverage: "Tech-Enabled Services",
    dealsShared: 2,
    lastInteraction: "2026-03-22",
    relationship: "warm",
    email: "k.zhao@hl.com",
    phone: "(212) 555-0887",
  },
  {
    id: "banker-4",
    name: "Alicia Brennan",
    firm: "Baird",
    title: "Senior Vice President",
    coverage: "Healthcare Services",
    dealsShared: 1,
    lastInteraction: "2026-02-14",
    relationship: "cold",
    email: "a.brennan@rwbaird.com",
    phone: "(414) 555-0219",
  },
  {
    id: "banker-5",
    name: "Thomas Nguyen",
    firm: "Raymond James",
    title: "Managing Director",
    coverage: "Distribution & Logistics",
    dealsShared: 2,
    lastInteraction: "2026-04-12",
    relationship: "active",
    email: "t.nguyen@raymondjames.com",
    phone: "(813) 555-0764",
  },
];

export const SEED_DEALS: Deal[] = [
  {
    id: "deal-1",
    companyName: "Apex Field Services",
    sector: "Industrials",
    revenue: 48,
    ebitda: 7.2,
    askMultiple: 7.5,
    impliedEV: 54,
    stage: "due_diligence",
    sourceType: "banker",
    sourcedFrom: "Lincoln International",
    processDeadline: "2026-05-15",
    entryDate: "2026-02-10",
    notes: "Strong route density. Management team rollover expected. QofE underway.",
    irr: 28,
    moic: 2.8,
    managementQuality: 4,
  },
  {
    id: "deal-2",
    companyName: "PrecisionTech Distribution",
    sector: "Distribution",
    revenue: 62,
    ebitda: 8.5,
    askMultiple: 8.0,
    impliedEV: 68,
    stage: "loi_sent",
    sourceType: "banker",
    sourcedFrom: "Harris Williams",
    processDeadline: "2026-05-30",
    entryDate: "2026-03-01",
    notes: "LOI submitted at $65M. Negotiating exclusivity. Seller wants fast close.",
    irr: 24,
    moic: 2.5,
    managementQuality: 4,
  },
  {
    id: "deal-3",
    companyName: "Cornerstone HR Solutions",
    sector: "Business Services",
    revenue: 22,
    ebitda: 3.8,
    askMultiple: 7.0,
    impliedEV: 26.6,
    stage: "initial_review",
    sourceType: "referral",
    sourcedFrom: "Richard Hargrove III",
    processDeadline: "2026-06-10",
    entryDate: "2026-03-20",
    notes: "Proprietary referral from LP. PEO/HRO crossover. Reviewing CIM now.",
    managementQuality: 3,
  },
  {
    id: "deal-4",
    companyName: "Brightwave Managed IT",
    sector: "Tech-Enabled Services",
    revenue: 18,
    ebitda: 4.1,
    askMultiple: 9.0,
    impliedEV: 36.9,
    stage: "passed",
    sourceType: "banker",
    sourcedFrom: "Houlihan Lokey",
    processDeadline: null,
    entryDate: "2026-01-15",
    notes: "Passed — valuation too rich at 9x. Low recurring revenue base for the ask.",
    managementQuality: 3,
  },
  {
    id: "deal-5",
    companyName: "Summit Environmental Services",
    sector: "Industrials",
    revenue: 35,
    ebitda: 5.6,
    askMultiple: 7.0,
    impliedEV: 39.2,
    stage: "negotiation",
    sourceType: "proprietary",
    sourcedFrom: "Cold Outreach",
    processDeadline: "2026-05-08",
    entryDate: "2025-11-01",
    notes: "Proprietary. 18-month relationship. Seller wants $40M. Working toward $38M.",
    irr: 31,
    moic: 3.1,
    managementQuality: 5,
  },
  {
    id: "deal-6",
    companyName: "Keystone Packaging Group",
    sector: "Industrials",
    revenue: 55,
    ebitda: 9.1,
    askMultiple: 7.2,
    impliedEV: 65.5,
    stage: "sourced",
    sourceType: "banker",
    sourcedFrom: "Raymond James",
    processDeadline: "2026-07-15",
    entryDate: "2026-04-20",
    notes: "Just received teaser. Broad process expected. Reviewing fit.",
    managementQuality: 3,
  },
  {
    id: "deal-7",
    companyName: "Verity Specialty Staffing",
    sector: "Business Services",
    revenue: 29,
    ebitda: 3.1,
    askMultiple: 6.5,
    impliedEV: 20.2,
    stage: "portfolio",
    sourceType: "proprietary",
    sourcedFrom: "Direct Outreach",
    processDeadline: null,
    entryDate: "2025-06-01",
    notes: "Closed Fund I Platform #1. 100-day plan underway. CFO hire in progress.",
    irr: 27,
    moic: 2.6,
    managementQuality: 4,
  },
  {
    id: "deal-8",
    companyName: "Ridgeline Safety Systems",
    sector: "Industrials",
    revenue: 41,
    ebitda: 6.8,
    askMultiple: 7.8,
    impliedEV: 53,
    stage: "initial_review",
    sourceType: "banker",
    sourcedFrom: "Baird",
    processDeadline: "2026-06-30",
    entryDate: "2026-04-01",
    notes: "Strong safety compliance niche. Reviewing management history and customer concentration.",
    managementQuality: 4,
  },
];

// ─── Sample deadline tasks demonstrating the time system ─────────────────────
// These four tasks are intentionally short-dated so advancing time past them
// demonstrates the deadline evaluation + missed-task consequences mechanic.

export const SAMPLE_DEADLINE_TASKS: Task[] = [
  {
    id: "deadline-1",
    title: "LP follow-up email — Vantage Point Capital",
    description: "Send James Cho a quick update: fund progress, two new LOIs in flight, re-confirm soft commit timeline. Due tomorrow.",
    category: "fundraising",
    priority: "high",
    status: "open",
    dueDate: "2026-04-30", // +1 day from sim start
    linkedLPId: "lp-3",
  },
  {
    id: "deadline-2",
    title: "Submit IOI — Apex Field Services",
    description: "Preliminary indication of interest to Lincoln International. Proposed EV range $50–56M. Needs GP sign-off before submission.",
    category: "deal",
    priority: "high",
    status: "open",
    dueDate: "2026-05-03", // +4 days
    linkedDealId: "deal-1",
  },
  {
    id: "deadline-3",
    title: "IC Memo — Summit Environmental Services",
    description: "Investment Committee memo covering thesis, management assessment, LBO returns, risks and mitigants. Full IC scheduled May 6.",
    category: "deal",
    priority: "high",
    status: "open",
    dueDate: "2026-05-06", // +7 days
    linkedDealId: "deal-5",
  },
  {
    id: "deadline-4",
    title: "Lender call — senior debt financing for Summit Environmental",
    description: "Intro call with Golub Capital and Antares to discuss leverage package for Summit. 4.5x senior / 5.5x total targeted.",
    category: "deal",
    priority: "medium",
    status: "open",
    dueDate: "2026-05-09", // +10 days
    linkedDealId: "deal-5",
  },
];

export const SEED_TASKS: Task[] = [
  ...SAMPLE_DEADLINE_TASKS,
  {
    id: "task-1",
    title: "Finalize QofE scope for Apex Field Services",
    description: "Confirm Quality of Earnings scope with Kroll. Agree on EBITDA add-backs list.",
    category: "deal",
    priority: "high",
    status: "open",
    dueDate: "2026-05-02",
    linkedDealId: "deal-1",
  },
  {
    id: "task-2",
    title: "Follow up with Vantage Point Capital on DDQ responses",
    description: "Send revised DDQ with performance attribution section. Request call to discuss.",
    category: "fundraising",
    priority: "high",
    status: "open",
    dueDate: "2026-05-05",
    linkedLPId: "lp-3",
  },
  {
    id: "task-3",
    title: "Submit IOI for PrecisionTech Distribution",
    description: "Management call review complete. Submit $65M IOI before process deadline.",
    category: "deal",
    priority: "high",
    status: "completed",
    dueDate: "2026-04-25",
    linkedDealId: "deal-2",
  },
  {
    id: "task-4",
    title: "Prepare Q1 LP update letter",
    description: "Draft fund update covering portfolio company performance and pipeline.",
    category: "lp_reporting",
    priority: "medium",
    status: "open",
    dueDate: "2026-05-15",
  },
  {
    id: "task-5",
    title: "Build LBO model for Summit Environmental",
    description: "Complete base/upside/downside cases. Sensitize on multiple and leverage.",
    category: "modeling",
    priority: "high",
    status: "open",
    dueDate: "2026-05-06",
    linkedDealId: "deal-5",
  },
  {
    id: "task-6",
    title: "Schedule management meeting — Cornerstone HR",
    description: "Coordinate with banker for management presentation. Bring deal team.",
    category: "deal",
    priority: "medium",
    status: "open",
    dueDate: "2026-05-20",
    linkedDealId: "deal-3",
  },
  {
    id: "task-7",
    title: "Verity Staffing: CFO candidate review",
    description: "Review shortlist from Korn Ferry. Interview top 3. Target hire by June 1.",
    category: "operations",
    priority: "high",
    status: "open",
    dueDate: "2026-05-10",
    linkedDealId: "deal-7",
  },
  {
    id: "task-8",
    title: "Send re-engagement note to Clearwater Pension",
    description: "Send materials ahead of their June board meeting. Include fund snapshot.",
    category: "fundraising",
    priority: "medium",
    status: "open",
    dueDate: "2026-05-25",
    linkedLPId: "lp-4",
  },
  {
    id: "task-9",
    title: "Review Keystone Packaging teaser",
    description: "Screen against mandate. Decide on CIM request. Flag to deal team.",
    category: "deal",
    priority: "low",
    status: "open",
    dueDate: "2026-05-30",
    linkedDealId: "deal-6",
  },
  {
    id: "task-10",
    title: "Negotiate Summit Environmental purchase agreement",
    description: "Markup SPA with counsel. Push back on reps and indemnification basket.",
    category: "deal",
    priority: "high",
    status: "open",
    dueDate: "2026-05-08",
    linkedDealId: "deal-5",
  },
];

export const SEED_EVENTS: EventFeedItem[] = [
  {
    id: "evt-1",
    date: "2026-04-29",
    type: "time_advance",
    title: "Simulation started",
    description: "Welcome to Arcadia Capital Partners I. Fund is in active fundraising. Three deals in late stages.",
    impact: "neutral",
  },
  {
    id: "evt-2",
    date: "2026-04-28",
    type: "deal_update",
    title: "Apex Field Services — QofE kickoff",
    description: "Quality of Earnings process kicked off with Kroll. Preliminary EBITDA confirmed at $7.2M TTM.",
    impact: "positive",
  },
  {
    id: "evt-3",
    date: "2026-04-25",
    type: "task_completed",
    title: "IOI submitted — PrecisionTech Distribution",
    description: "Indication of Interest submitted at $65M EV. Seller acknowledged receipt. Awaiting process update.",
    impact: "positive",
  },
  {
    id: "evt-4",
    date: "2026-04-20",
    type: "deal_update",
    title: "Keystone Packaging teaser received",
    description: "Raymond James sent teaser for Keystone Packaging Group ($55M revenue). Broad process. Reviewing mandate fit.",
    impact: "neutral",
  },
  {
    id: "evt-5",
    date: "2026-04-18",
    type: "lp_update",
    title: "Call with Michael Torres (Lincoln Int'l)",
    description: "Michael flagged two potential Q3 processes. Invited deal team to preview next week.",
    impact: "positive",
  },
  {
    id: "evt-6",
    date: "2026-04-15",
    type: "lp_update",
    title: "Meridian Endowment — IC approval advancing",
    description: "Patricia Walsh confirmed IC meeting scheduled for May 20. Full commitment of $20M likely to close.",
    impact: "positive",
  },
  {
    id: "evt-7",
    date: "2026-04-12",
    type: "deal_update",
    title: "Summit Environmental — exclusivity discussions",
    description: "Seller agreed to a two-week exclusivity period. Counsel engaged for SPA drafting.",
    impact: "positive",
  },
  {
    id: "evt-8",
    date: "2026-04-10",
    type: "lp_update",
    title: "Thornwood HNW — initial call",
    description: "Introductory call with Daniel Park. Positive tone. Sent fund deck and sample LP report.",
    impact: "neutral",
  },
  {
    id: "evt-9",
    date: "2026-04-05",
    type: "deal_update",
    title: "Brightwave Managed IT — passed",
    description: "Passed on Brightwave at 9x ask. Notified Caroline Strickland. Maintained banker relationship.",
    impact: "neutral",
  },
  {
    id: "evt-10",
    date: "2026-04-01",
    type: "deal_update",
    title: "Ridgeline Safety Systems — CIM received",
    description: "Full CIM received from Baird. Screening against mandate. Customer concentration noted.",
    impact: "neutral",
  },
  {
    id: "evt-11",
    date: "2026-03-28",
    type: "lp_update",
    title: "Vantage Point Capital — DDQ submitted",
    description: "Responded to DDQ. James Cho flagged he wants to see deal pipeline progress before committing.",
    impact: "neutral",
  },
  {
    id: "evt-12",
    date: "2026-03-22",
    type: "modeling",
    title: "LBO model — Apex completed",
    description: "Initial LBO model shows 26-30% IRR range. Base case 2.7x MOIC on 5-year hold. Sent to IC.",
    impact: "positive",
  },
  {
    id: "evt-13",
    date: "2026-03-15",
    type: "lp_update",
    title: "Hargrove Family Office — final close confirmed",
    description: "Richard Hargrove confirmed full $15M commitment. Wire instructions sent. Closes at next quarterly date.",
    impact: "positive",
  },
  {
    id: "evt-14",
    date: "2026-03-01",
    type: "deal_update",
    title: "PrecisionTech Distribution — management call",
    description: "Strong management call. CEO has been with company 11 years. Margin expansion thesis intact.",
    impact: "positive",
  },
  {
    id: "evt-15",
    date: "2026-02-20",
    type: "lp_update",
    title: "Clearwater Pension — first meeting",
    description: "Initial pitch to Susan Olawale. Positive feedback. Long lead time expected — board meets in June.",
    impact: "neutral",
  },
  {
    id: "evt-16",
    date: "2026-02-10",
    type: "deal_update",
    title: "Apex Field Services — entered due diligence",
    description: "Signed LOI. Management team fully engaged. QofE, legal, and environmental diligence tracks initiated.",
    impact: "positive",
  },
  {
    id: "evt-17",
    date: "2026-01-14",
    type: "lp_update",
    title: "Clearwater Pension — introduction via network",
    description: "Introduction to Clearwater Pension through Meridian Endowment network. Scheduled intro call.",
    impact: "positive",
  },
  {
    id: "evt-18",
    date: "2026-01-05",
    type: "reputation_change",
    title: "Fund reputation milestone: 47%",
    description: "Committed capital at 47% of target. Reputation score upgraded on fundraising progress.",
    impact: "positive",
  },
  {
    id: "evt-19",
    date: "2025-11-01",
    type: "deal_update",
    title: "Summit Environmental — proprietary sourcing",
    description: "18-month outreach campaign resulted in seller engagement. Confidentiality agreement signed.",
    impact: "positive",
  },
  {
    id: "evt-20",
    date: "2025-06-01",
    type: "deal_update",
    title: "Verity Specialty Staffing — closed",
    description: "Fund I platform investment #1 closed at $20.2M EV. 100-day value creation plan launched.",
    impact: "positive",
  },
];

export const INITIAL_STATE: SimulationState = {
  currentDate: "2026-04-29",
  fund: SEED_FUND,
  lps: SEED_LPS,
  bankers: SEED_BANKERS,
  deals: SEED_DEALS,
  tasks: SEED_TASKS,
  eventFeed: SEED_EVENTS,
  reputationScore: 62,
  modelingSkillScore: 55,
};
