-- ============================================================================
-- PE Fund Simulator — Initial Schema
-- Migration: 20260429000001_initial_schema.sql
-- ============================================================================
-- Primary keys are TEXT (not UUID) so the application-level IDs such as
-- "fund-1", "task-3", "deal-7" carry through without a translation layer.
-- Dates are stored as TEXT in ISO-8601 format (YYYY-MM-DD) to match the
-- simulator's internal date representation exactly.
-- ============================================================================

-- ---------------------------------------------------------------------------
-- 1. Users
--    One row per browser session. The ID is a UUID generated by the client
--    on first visit and persisted in localStorage under "pe-sim-user-id".
--    No Supabase Auth is required for the single-player MVP.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS users (
  id            TEXT PRIMARY KEY,
  display_name  TEXT NOT NULL DEFAULT 'Fund Manager',
  created_at    TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ---------------------------------------------------------------------------
-- 2. Funds
--    One fund per user for the current MVP (Fund I).
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS funds (
  id                       TEXT PRIMARY KEY,
  user_id                  TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  name                     TEXT NOT NULL,
  vintage                  INTEGER,
  target_size              NUMERIC,           -- $M
  committed_capital        NUMERIC DEFAULT 0, -- $M
  called_capital           NUMERIC DEFAULT 0, -- $M
  strategy                 TEXT,
  sector                   TEXT,
  geography                TEXT,
  revenue_min              NUMERIC,           -- $M
  revenue_max              NUMERIC,           -- $M
  ebitda_min               NUMERIC,           -- $M
  ebitda_max               NUMERIC,           -- $M
  funding_status           TEXT NOT NULL DEFAULT 'fundraising',
  management_fee           NUMERIC,           -- %
  carry                    NUMERIC,           -- %
  investment_period_years  INTEGER,
  fund_life_years          INTEGER,
  created_at               TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at               TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ---------------------------------------------------------------------------
-- 3. Simulation State
--    Scalar simulation metadata (current date, scores).
--    One row per user — user_id is both the PK and FK.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS simulation_state (
  user_id               TEXT PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
  fund_id               TEXT REFERENCES funds(id) ON DELETE SET NULL,
  current_date          TEXT NOT NULL,   -- ISO-8601 e.g. "2026-04-29"
  reputation_score      INTEGER NOT NULL DEFAULT 62,
  modeling_skill_score  INTEGER NOT NULL DEFAULT 55,
  updated_at            TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ---------------------------------------------------------------------------
-- 4. LP Prospects
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS lp_prospects (
  id                  TEXT PRIMARY KEY,
  user_id             TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  fund_id             TEXT REFERENCES funds(id) ON DELETE SET NULL,
  name                TEXT NOT NULL,
  type                TEXT,  -- "family_office" | "endowment" | "pension" | ...
  target_commitment   NUMERIC,
  committed_amount    NUMERIC DEFAULT 0,
  status              TEXT NOT NULL DEFAULT 'prospect',
  contact_name        TEXT,
  contact_title       TEXT,
  location            TEXT,
  introduction_date   TEXT,  -- ISO-8601
  last_contact_date   TEXT,  -- ISO-8601
  notes               TEXT,
  tier                INTEGER,
  created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ---------------------------------------------------------------------------
-- 5. Contacts (investment bankers and other deal-flow sources)
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS contacts (
  id                TEXT PRIMARY KEY,
  user_id           TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  name              TEXT NOT NULL,
  firm              TEXT,
  title             TEXT,
  coverage          TEXT,   -- sector coverage
  deals_shared      INTEGER DEFAULT 0,
  last_interaction  TEXT,   -- ISO-8601
  relationship      TEXT,   -- "active" | "warm" | "cold" | "inactive"
  email             TEXT,
  phone             TEXT,
  created_at        TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ---------------------------------------------------------------------------
-- 6. Deals
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS deals (
  id                  TEXT PRIMARY KEY,
  user_id             TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  fund_id             TEXT REFERENCES funds(id) ON DELETE SET NULL,
  company_name        TEXT NOT NULL,
  sector              TEXT,
  revenue             NUMERIC,        -- $M TTM
  ebitda              NUMERIC,        -- $M TTM
  ask_multiple        NUMERIC,        -- EV/EBITDA
  implied_ev          NUMERIC,        -- $M
  stage               TEXT NOT NULL DEFAULT 'sourced',
  source_type         TEXT,           -- "banker" | "proprietary" | "referral" | "sponsor"
  sourced_from        TEXT,
  process_deadline    TEXT,           -- ISO-8601 or NULL
  entry_date          TEXT,           -- ISO-8601
  notes               TEXT,
  irr                 NUMERIC,        -- % projected
  moic                NUMERIC,        -- x projected
  management_quality  INTEGER,        -- 1-5
  created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ---------------------------------------------------------------------------
-- 7. Tasks
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS tasks (
  id              TEXT PRIMARY KEY,
  user_id         TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  fund_id         TEXT REFERENCES funds(id) ON DELETE SET NULL,
  title           TEXT NOT NULL,
  description     TEXT,
  category        TEXT,   -- "deal" | "fundraising" | "lp_reporting" | ...
  priority        TEXT,   -- "high" | "medium" | "low"
  status          TEXT NOT NULL DEFAULT 'open',  -- "open" | "completed" | "missed"
  due_date        TEXT,   -- ISO-8601
  linked_deal_id  TEXT REFERENCES deals(id) ON DELETE SET NULL,
  linked_lp_id    TEXT REFERENCES lp_prospects(id) ON DELETE SET NULL,
  created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ---------------------------------------------------------------------------
-- 8. Events (simulation event feed)
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS events (
  id           TEXT PRIMARY KEY,
  user_id      TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  event_date   TEXT NOT NULL,  -- ISO-8601
  type         TEXT NOT NULL,  -- "deal_update" | "lp_update" | "task_missed" | ...
  title        TEXT NOT NULL,
  description  TEXT,
  impact       TEXT,           -- "positive" | "negative" | "neutral"
  created_at   TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ---------------------------------------------------------------------------
-- 9. Modeling Submissions
--    Records each time the user saves an LBO model scenario.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS modeling_submissions (
  id                  TEXT PRIMARY KEY DEFAULT gen_random_uuid()::TEXT,
  user_id             TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  deal_id             TEXT REFERENCES deals(id) ON DELETE SET NULL,
  entry_ev            NUMERIC,
  entry_debt          NUMERIC,
  revenue_growth      NUMERIC,
  ebitda_margin_exit  NUMERIC,
  exit_multiple       NUMERIC,
  hold_years          INTEGER,
  projected_irr       NUMERIC,
  projected_moic      NUMERIC,
  submitted_at        TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ============================================================================
-- Indexes
-- ============================================================================
CREATE INDEX IF NOT EXISTS idx_funds_user_id          ON funds(user_id);
CREATE INDEX IF NOT EXISTS idx_lp_prospects_user_id   ON lp_prospects(user_id);
CREATE INDEX IF NOT EXISTS idx_lp_prospects_fund_id   ON lp_prospects(fund_id);
CREATE INDEX IF NOT EXISTS idx_contacts_user_id       ON contacts(user_id);
CREATE INDEX IF NOT EXISTS idx_deals_user_id          ON deals(user_id);
CREATE INDEX IF NOT EXISTS idx_deals_fund_id          ON deals(fund_id);
CREATE INDEX IF NOT EXISTS idx_tasks_user_id          ON tasks(user_id);
CREATE INDEX IF NOT EXISTS idx_tasks_due_date         ON tasks(due_date);
CREATE INDEX IF NOT EXISTS idx_tasks_linked_deal_id   ON tasks(linked_deal_id);
CREATE INDEX IF NOT EXISTS idx_events_user_id         ON events(user_id);
CREATE INDEX IF NOT EXISTS idx_events_event_date      ON events(event_date);
CREATE INDEX IF NOT EXISTS idx_modeling_user_id       ON modeling_submissions(user_id);

-- ============================================================================
-- Row Level Security
-- ============================================================================
-- For the single-player simulator MVP we enable permissive policies using the
-- anonymous key.  In a multi-tenant production deployment, replace these with
-- auth.uid()::text = user_id checks and proper Supabase Auth integration.
-- ============================================================================
ALTER TABLE users               ENABLE ROW LEVEL SECURITY;
ALTER TABLE funds               ENABLE ROW LEVEL SECURITY;
ALTER TABLE simulation_state    ENABLE ROW LEVEL SECURITY;
ALTER TABLE lp_prospects        ENABLE ROW LEVEL SECURITY;
ALTER TABLE contacts            ENABLE ROW LEVEL SECURITY;
ALTER TABLE deals               ENABLE ROW LEVEL SECURITY;
ALTER TABLE tasks               ENABLE ROW LEVEL SECURITY;
ALTER TABLE events              ENABLE ROW LEVEL SECURITY;
ALTER TABLE modeling_submissions ENABLE ROW LEVEL SECURITY;

-- Permissive policies — allow the anon key to read and write freely.
-- NOTE: These are intentionally open for local development / single-user use.
--       Lock down with auth.uid() checks before going multi-user / public.
DO $$
DECLARE
  t TEXT;
BEGIN
  FOREACH t IN ARRAY ARRAY[
    'users', 'funds', 'simulation_state', 'lp_prospects',
    'contacts', 'deals', 'tasks', 'events', 'modeling_submissions'
  ] LOOP
    EXECUTE format(
      'CREATE POLICY "anon_all_%s" ON %I FOR ALL USING (true) WITH CHECK (true)',
      t, t
    );
  END LOOP;
END $$;

-- ============================================================================
-- Updated-at trigger for funds and simulation_state
-- ============================================================================
CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$;

CREATE TRIGGER funds_updated_at
  BEFORE UPDATE ON funds
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER simulation_state_updated_at
  BEFORE UPDATE ON simulation_state
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();
